// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/telegram-bot-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"approve_suggested_post | decline_suggested_post | delete_forum_topic | edit_forum_topic | file | forum_topic | get_business_account_gift | get_chat_gift | get_me | get_user_gift | get_user_profile_audio | message | message_id | promote_chat_member | remove_my_profile_photo | repost_story | send_chat_action | send_message_draft | set_my_profile_photo | unpin_all_forum_topic_message | update"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.TelegramBotSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "telegram-bot_list",
		Description: "List records from TelegramBot. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "telegram-bot_load",
		Description: "Load a single record from TelegramBot. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.TelegramBotSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.TelegramBotSDK, name string) (sdk.TelegramBotEntity, error) {
	switch strings.ToLower(name) {
	case "approve_suggested_post":
		return client.ApproveSuggestedPost(nil), nil
	case "decline_suggested_post":
		return client.DeclineSuggestedPost(nil), nil
	case "delete_forum_topic":
		return client.DeleteForumTopic(nil), nil
	case "edit_forum_topic":
		return client.EditForumTopic(nil), nil
	case "file":
		return client.File(nil), nil
	case "forum_topic":
		return client.ForumTopic(nil), nil
	case "get_business_account_gift":
		return client.GetBusinessAccountGift(nil), nil
	case "get_chat_gift":
		return client.GetChatGift(nil), nil
	case "get_me":
		return client.GetMe(nil), nil
	case "get_user_gift":
		return client.GetUserGift(nil), nil
	case "get_user_profile_audio":
		return client.GetUserProfileAudio(nil), nil
	case "message":
		return client.Message(nil), nil
	case "message_id":
		return client.MessageId(nil), nil
	case "promote_chat_member":
		return client.PromoteChatMember(nil), nil
	case "remove_my_profile_photo":
		return client.RemoveMyProfilePhoto(nil), nil
	case "repost_story":
		return client.RepostStory(nil), nil
	case "send_chat_action":
		return client.SendChatAction(nil), nil
	case "send_message_draft":
		return client.SendMessageDraft(nil), nil
	case "set_my_profile_photo":
		return client.SetMyProfilePhoto(nil), nil
	case "unpin_all_forum_topic_message":
		return client.UnpinAllForumTopicMessage(nil), nil
	case "update":
		return client.Update(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
